source 'git@git.superid.cn:iOS/SISpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

target 'SIBase_Example' do
  pod 'SIBase', :path => '../'

  target 'SIBase_Tests' do
    inherit! :search_paths

    
  end
end
